/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Object_Oriented_Programmings_NativeClass */

#ifndef _Included_Object_Oriented_Programmings_NativeClass
#define _Included_Object_Oriented_Programmings_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Object_Oriented_Programmings_NativeClass
 * Method:    declare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Object_1Oriented_1Programmings_NativeClass_declare
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
